version: '3'
 
services:

    nginx:
        ports:
            - 3000:80

    node-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        # stdin_open: true      # docker run -i
        # tty: true             # docker run -t
        volumes:
            - ./:/node-app
            # - /node-app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
